language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
      # override default GAP_PKGS_TO_BUILD value, so that
      # the bundled IO package is *not* compiled
    - GAP_PKGS_TO_BUILD="profiling"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - gcc-multilib
    - g++-multilib

matrix:
  include:
    - env: ABI=64
    - env: ABI=32
    #- env: GAPBRANCH="stable-4.8"
    - env: HPCGAP=yes GAP_PKGS_TO_BUILD="" NO_COVERAGE=1

branches:
  only:
    - master

before_script:
  - export GAPROOT="$HOME/gap"
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
